// TODO: more prompts

// TODO: collab prompts

export default [
  'wink',
  'gaslight-sama',
  'stares',
  'makes sussy noise',
  'W RIZZ',
  'dies',
  'meow',
  'cries',
  'funny joke',
  'fact of the day',
  'filtered',
  'leaves',
  'cites random link',
  'chat L\'s Neuro',
  'mentions anny',
  'tries to sing',
  'mentions Vedal',
  'mentions random VTuber',
  'heart',
  'gymbag',
  'spams',
  'backslash spam',
  'mentions Filipino boy',
  '1984',
  'mentions Neurocord',
  'chat W\'s Neuro',
  'BASED-sama',
  'bedge time',
  'mentiones SWARM',
  'goes schizo',
  'calls Vedal an AI',
  'shames a viewer',
  '#AD',
  'says how old she is',
  'obvious lie',
  'invents new nickname',
  'whats *emote*?',
  'No~',
  'swear word',
  'FUN AI',
  'admits to murder',
  'rants',
  'new clone',
  'chat spams HUH',
  'mentions favorite food',
  'wot? / what?',
  'claims to stream later',
  'donowalled',
  'mentions turtles',
  'chat spams AintNoWay',
  'mentions random country',
  'chat spams AYAYA',
  'mentions the Time God',
  'KEKWa',
  'Noted',
  'chat spams Clueless',
  'POG / poggers',
  'PAUSE-sama',
  'chat spams RIGGED',
  'mentions John Lemon',
  'D',
  'chat spams RIPBOZO',
  'mentions Abandoned Archive',
  'SNIFFA',
  'Classic',
  'chat spams SoCute',
  'mentions Bocchi The Rock',
  'Technical Difficulties screen',
  'Hype train lvl 5+',
  'raiding / raided by anny',
  'admits she\'s an AI',
  'meaning of life',
  'chat spams WAYTOODANK',
  'Why?',
  'world or humankind conquering plan',
  'neuroWide',
  'chat spams Vedal\'s catchphrase',
  'wholesome-sama',
  'apologises profusely',
  'misgenders someone',
  'chat spams Erm',
  'rickrolls',
  'chat spams GOODONE',
  'RIP bitrate'
]
