// TODO: more prompts

// TODO: collab prompts

export default [
  'wink',
  'gaslight-sama',
  'stare',
  'makes sussy noise',
  'W RIZZ',
  'dies',
  'meow',
  'cries',
  'funny joke',
  'fact of the day',
  'filtered',
  'leaves',
  'cites random link',
  'chat L\'s Neuro',
  'mentions anny',
  'tries to sing',
  'mentions Vedal',
  'mentions random VTuber',
  'heart',
  'gymbag',
  'spams',
  'backslash spam',
  'mentions Filipino boy',
  '1984',
  'accept bits ignores message',
  'mentions Neurocord',
  'chat W\'s Neuro',
  'BASED-sama',
  'bedge time',
  'SWARM mentioned',
  'goes schizo',
  'calls Vedal an AI',
  'shames random Twitch viewer',
  '#AD',
  'says how old she is',
  'obvious lie',
  'invents new nickname',
  'whats *emote*?',
  'No~',
  'swear word',
  'FUN AI',
  'admits to murder',
  'rants',
  'new clone'
]
